version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on: 
      - client
      - api
    links:
      - client
      - api
    ports:
      - '3050:80'
  postgres:
    image: 'postgres:latest'
  redis: 
    image: 'redis:latest'
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - redis
      - postgres
      - worker
    links:
      - redis
      - postgres
      - worker
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGDPASSWORD=postgres_password
      - PGDPORT=5432
  client: 
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    depends_on: 
      - api
    links: 
      - api
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    depends_on: 
      - redis
    links: 
      - redis
    volumes: 
      - /app/node_modules
      - ./worker:/app
      
      